### ISSUE TITLE
Tutilgan ro'za kunlari uchun checkbox qo'yish

### ISSUE THREAD

**Issue by hurram-dev** [hurram-dev/ramadan-taqvim-app#3]
30 kunlik ramazon taqvimi table da, ro'za tutilgan kunlar uchun checkbox qo'yish. Bu "Kun" columnidan keyingi columnda joylashishi kerak.

**Comment by riyashivolkar** [comment]
I have made the changes, getting  errorr for push , access denied
<img width="696" alt="Screenshot 2024-03-12 152226" src="https://github.com/hurram-dev/ramadan-taqvim-app/assets/64467020/c14fdd22-e974-422f-b087-07b479d50f6b">

**Comment by hurram-dev** [comment]
`main` branch is protected due to prevent unnecessary push by people. You better to create Pull Request (PR) to main as a base. I will review your PR and if everything OK, we will merge it to main

**Comment by hurram-dev** [comment]
@riyashivolkar  did you figure out what feature is required in this issue?

**Comment by riyashivolkar** [comment]
Check Box for observed fast days as u described.

**Comment by hurram-dev** [comment]
Done at #5 PR
